/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const externalprod_Logic = require('./code/externalprod-logic');

class cap_ext_servService extends LCAPApplicationService {
    async init() {

        this.on('READ', 'ExternalProd', async (request, next) => {
            return externalprod_Logic(request, next);
        });

        return super.init();
    }
}


module.exports = {
    cap_ext_servService
};